### mysql select
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "cnapp.db.mysql",
  "actionName": "MySqlQueryAction",
  "params": {
    "connString": "jdbc:mysql://localhost:8082/socksdb?user=root&password=fake_password",
    "query": "select * from sock"
  }
}

### mysql update
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "cnapp.db.mysql",
  "actionName": "MySqlUpdateAction",
  "params": {
    "connString": "jdbc:mysql://localhost:33061/socksdb?user=root&password=fake_password",
    "query": "update sock set price = 15 where name = 'SuperSport XL'"
  }
}
