### delete user
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "cnapp.sockshop",
  "actionName": "DeleteUserAction",
  "params": {
    "applicationUrl": "http://localhost:8082",
    "userId": "655cd9edcb8de600019db12f"
  }
}
