### create volume snapshot
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "CreateVolumeSnapshotAction",
  "params": {
    "params": {
      "region": "RegionOne",
      "volumeId": "PUT_ID"
    }
  }
}


### create volume snapshot with specific name
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "CreateVolumeSnapshotAction",
  "params": {
    "params": {
      "region": "RegionOne",
      "volumeId": "PUT_ID",
      "snapshotName": "volume-snapshot-test"
    }
  }
}