### change resources of a container
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "ChangeResourcesOfContainerWithinDeploymentAction",
  "params": {
    "namespace": "default",
    "deploymentName": "change-resources-test",
    "containerName": "nginx",
    "limitsCpu": "400m",
    "limitsMemory": "250Mi",
    "requestsCpu": "250m",
    "requestsMemory": "100Mi"
  }
}

###### setUp
### add deployment with resources
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "AddResourceAction",
  "params": {
    "namespace": "default",
    "resourceDescription": "apiVersion: apps/v1\r\nkind: Deployment\r\nmetadata:\r\n  name: change-resources-test\r\n  labels:\r\n    app: nginx\r\nspec:\r\n  replicas: 3\r\n  selector:\r\n    matchLabels:\r\n      app: nginx\r\n  template:\r\n    metadata:\r\n      labels:\r\n        app: nginx\r\n    spec:\r\n      containers:\r\n      - name: nginx\r\n        image: nginx:1.14.2\r\n        resources:\r\n          limits:\r\n            cpu: 900m\r\n            memory: 900Mi\r\n          requests:\r\n            cpu: 900m\r\n            memory: 900Mi\r\n        ports:\r\n        - containerPort: 80\r\n"
  }
}

###### tearDown
### delete deployment with resources
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "DeleteResourceAction",
  "params": {
    "resourceType": "Deployment",
    "resourceName": "change-resources-test",
    "namespace": "default",
    "gracePeriodSeconds": "60"
  }
}
