### delete pod
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "DeleteResourceAction",
  "params": {
      "resourceType": "Pod",
      "resourceName": "nginx",
      "namespace": "default",
      "gracePeriodSeconds": "60"
  }
}

### delete config map
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "DeleteResourceAction",
  "params": {
      "resourceType": "ConfigMap",
      "resourceName": "cm1",
      "namespace": "default"
  }
}
