### update config map
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "UpdateConfigMapAction",
  "params": {
      "resourceName": "cm1",
      "namespace": "default",
      "k1": "k55",
      "v1": "v55"
  }
}
