### custom tcp inbound ipv4 port 80 rule
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "AddRuleToSecurityGroupAction",
  "params": {
    "region": "RegionOne",
    "securityGroupId": "PUT_ID",
    "ethertype": "IPv4",
    "direction": "ingress",
    "remoteIpPrefix": "172.42.0.0/16",
    "protocol": "TCP",
    "portRangeMin": "80",
    "portRangeMax": "80",
    "description": "optional description"
  }
}
