### IP Throttle with custom tcp outbound ipv4 port 80 rule (group exists for 5 min by default)
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "IpThrottleAction",
  "params": {
    "params": {
      "region": "RegionOne",
      "serverId": "d0f0afdb-051b-4462-add3-bd51fe427541",
      "ethertype": "IPv4",
      "remoteIpPrefix": "192.168.1.160/27",
      "protocol": "TCP",
      "portRangeMin": "80",
      "portRangeMax": "80"
    }
  }
}

