### remove rule
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "RemoveRuleFromSecurityGroupAction",
  "params": {
    "region": "RegionOne",
    "securityGroupRuleId": "PUT_ID"
  }
}
