### custom script
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "command",
  "actionName": "CustomScriptAction",
  "params": {
      "host": "",
      "port": "22",
      "privateKey": "",
      "user": "ubuntu",
      "command": "echo \"Hello $(whoami)\""
  }
}
