### change resources of a container
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "ChangeResourcesOfContainerWithinPodAction",
  "params": {
    "params": {
      "namespace": "default",
      "podName": "change-resources-test",
      "containerName": "nginx",
      "limitsCpu": "300m",
      "limitsMemory": "350Mi",
      "requestsCpu": "200m",
      "requestsMemory": "300Mi"
    }
  }
}
