### resize to h2.medium
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "VerticalScalingUpAction",
  "params": {
    "params": {
      "region": "RegionOne",
      "serverId": "PUT_ID",
      "flavorId": "414a6a89-57c3-4331-9a05-0a53fc9a7d02"
    }
  }
}

### resize to h1.smedium
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "VerticalScalingUpAction",
  "params": {
    "params": {
      "region": "RegionOne",
      "serverId": "453045c4-b6c2-4031-95b4-ac3003ecc66b",
      "flavorId": "13a343c9-1fc5-4dae-9a74-203d290d736b"
    }
  }
}

### resize to c1.small
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "VerticalScalingUpAction",
  "params": {
    "params": {
      "region": "RegionOne",
      "serverId": "1a85eefb-fcd2-40f1-a170-247e5ac111dc",
      "flavorId": "f2559863-ef7d-416c-907e-4ea4043d4831"
    }
  }
}
