apiVersion: v1
kind: Service
metadata:
  name: themis-executor-service
  namespace: themis-executor
spec:
  type: ClusterIP
  selector:
    name: themis-executor
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080