---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: themis-executor
  labels:
    app: themis-executor
    name: themis-executor
  namespace: themis-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: themis-executor
  template:
    metadata:
      labels:
        name: themis-executor
    spec:
      serviceAccountName: themis-executor
      containers:
        - name: executor
          image: agwen12/themis-executor:0.0.2.2
          env:
            - name: RULES_PATH
              value: /rules/test.drl
            - name: HEPHAESTUS_URL #hephaestus
              value: http://hephaestus-gui.hephaestus.svc.cluster.local:8080
            - name: KUBERNETES_MASTER_URL
              value: https://149.156.10.131:6443
            - name: KUBERNETES_CA_CERT_DATA
              value: 
            - name: KUBERNETES_CLIENT_CERT_DATA
              value: 
            - name: KUBERNETES_CLIENT_KEY_DATA
              value: 
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: rules-volume
              mountPath: /rules
      volumes:
        - name: rules-volume
          configMap:
            name: executor-rules-cm
