### delete volume snapshot
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "DeleteVolumeSnapshotAction",
  "params": {
      "region": "RegionOne",
      "volumeId": "PUT_ID"
  }
}


### delete volume snapshot with flag keepOneSnapshot = false
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "DeleteVolumeSnapshotAction",
  "params": {
      "region": "RegionOne",
      "volumeId": "PUT_ID",
      "keepOneSnapshot": "false"
  }
}