POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "HorizontalScalingAction",
  "params": {
    "params": {
      "resourceType": "Deployment",
      "resourceName": "nginx-deployment",
      "namespace": "default",
      "replicas": "1"
    }
  }
}

###
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "UpdateConfigMapAction",
  "params": {
    "params": {
      "resourceName": "cm1",
      "namespace": "default",
      "k1": "k55",
      "v1": "v55"
    }
  }
}

###
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "UpdateConfigMapAction",
  "params": {
    "params": {
      "resourceName": "cm1",
      "namespace": "default",
      "k1": "k1",
      "v1": "v100"
    }
  }
}

###
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "DeleteResourceAction",
  "params": {
    "params": {
      "resourceType": "Pod",
      "resourceName": "nginx",
      "namespace": "default",
      "gracePeriodSeconds": "60"
    }
  }
}

###
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "kubernetes",
  "actionName": "DeleteResourceAction",
  "params": {
    "params": {
      "resourceType": "ConfigMap",
      "resourceName": "cm1",
      "namespace": "default"
    }
  }
}
