### send mail
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "cnapp.mail",
  "actionName": "SendMailAction",
  "params": {
    "receiver": "k8loud@int.pl",
    "senderDisplayName": "Themis Executor",
    "subject": "Test mail",
    "content": "empty"
  }
}

### send mail with embedded images
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "cnapp.mail",
  "actionName": "SendMailAction",
  "params": {
    "receiver": "k8loud@int.pl",
    "senderDisplayName": "Themis Executor",
    "subject": "Test mail",
    "content": "empty",
    "imageTitleToPath": "img1=/media/shared/Documents/agh/inzynierka/repos/themis-executor/src/test/java/org/k8loud/executor/actions/cnapp/mail/http/hedgehog1.jpg,img2=/media/shared/Documents/agh/inzynierka/repos/themis-executor/src/test/java/org/k8loud/executor/actions/cnapp/mail/http/hedgehog2.jpg"
  }
}
