package org.k8loud.executor.exception.code;

public enum CNAppExceptionCode {
    SOCK_SHOP_REGISTER_USER_FAILED,
    SOCK_SHOP_DELETE_USER_FAILED,
    SOCK_SHOP_CREATE_ADDRESS_FAILED,
    SOCK_SHOP_DELETE_ADDRESS_FAILED,

    CAUGHT_HTTP_EXCEPTION
}
