package org.k8loud.executor.exception.code;

public enum KubernetesExceptionCode {
    SCALE_HORIZONTALLY_FAILED,
    ADD_RESOURCE_FAILED,
    DELETE_RESOURCE_FAILED,
    UPDATE_CONFIG_MAP_FAILED,
    CHANGE_RESOURCES_OF_CONTAINER_WITHIN_POD_FAILED,

    INVALID_RESOURCE_TYPE,
    RESOURCE_NOT_FOUND,
    EMPTY_OR_BLANK_NAMESPACE,
    EMPTY_OR_BLANK_RESOURCE_NAME,
    RESOURCE_FILE_NOT_EXISTS,
    RESOURCE_ALREADY_EXISTS,
    POST_ADD_RESOURCE_VERIFICATION_FAILED,
    CONTAINER_WITHIN_POD_NOT_FOUND,
    EMPTY_SPEC
}
