package org.k8loud.executor.exception.code;

public enum OpenstackExceptionCode {
    TOKEN_INVALID,
    AUTHENTICATION_ERROR,
    SERVER_NOT_EXISTS,
    FLAVOR_NOT_EXITS,
    VOLUME_NOT_EXITS,
    RESIZE_SERVER_FAILED,
    FLAVORS_DISKS_NOT_SAME,
    FLAVORS_COMPARISON,
    COPY_SERVER_FAILED,
    ATTACH_VOLUME_FAILED,
    VOLUME_ERROR,
    DETACH_VOLUME_FAILED,
}
