### create server snapshot
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "CreateServerSnapshotAction",
  "params": {
    "region": "RegionOne",
    "serverId": "PUT_ID"
  }
}

### create server snapshot with optional name
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "CreateServerSnapshotAction",
  "params": {
    "region": "RegionOne",
    "serverId": "PUT_ID",
    "snapshotName": "Snapshot-name-test"
  }
}

### create server snapshot on stopped server
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "CreateServerSnapshotAction",
  "params": {
    "region": "RegionOne",
    "serverId": "PUT_ID",
    "stopInstance": "true"
  }
}
