### delete instances
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "DeleteInstanceAction",
  "params": {
    "region": "RegionOne",
    "namePattern": "kube-worker-quick-spawn-test-020f4280"
  }
}

### delete specific instances
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "DeleteInstanceAction",
  "params": {
    "region": "RegionOne",
    "serverIds": "id1,id2,...,idN"
  }
}
