### delete instances
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "DeleteInstanceAction",
  "params": {
      "region": "RegionOne",
      "name": "test"
  }
}

### delete specific instances
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "DeleteInstanceAction",
  "params": {
      "region": "RegionOne",
      "name": "anything",
      "serverIds": "id1,id2,...,idN"
  }
}