### pause server
POST localhost:8080/execute
Content-Type: application/json

{
  "collectionName": "openstack",
  "actionName": "PauseServerAction",
  "params": {
    "params": {
      "region": "RegionOne",
      "serverId": "d0f0afdb-051b-4462-add3-bd51fe427541"
    }
  }
}
