apiVersion: v1
kind: Secret
metadata:
  name: themis-secrets
  namespace: themis-executor-ppycia
type: Opaque
data:
  MAIL_PASSWORD: bGlzdG9ub3N6cGF0MTIzCg==
  OPENSTACK_PASSWORD: UHljaWEhTXlzem9qZWxlbkBkb3QuY29tMjEzNw==
---
apiVersion: v1
kind: Secret
metadata:
  name: themis-secrets-k8s
  namespace: themis-executor-ppycia
type: Opaque
stringData:
  KUBERNETES_CA_CERT_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRTFGTVBRK0NZWkV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1qWXhOak0xTkRaYUZ3MHpNekV4TWpNeE5qUXdORFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURZQ3YvL05Hdm9KdkNqQWNqUWllK1JxNmNmSy80aVFtNFI0NEQ4WFpoTk1UQzFQYURQNDM1aE5yOGYKbnVEaU0ydWUrbmVnZnRrSm5WUUY3YXZWN2RZTk5Zcm5KZmtPU3ZJR3hzRzRKL1pPZkRzLy9pWWw2OE5pdklxRQpLVit0TWVxMlFKQ1lYbkRuOGhLcEx6a0R3WCt0bnhnZXhVS29Kc0JMK0FocUY1amV1M0hZU2dVMGhzQ0o1KzZmCnlubDlLSEpOWXZ2Q1I0ZWZLeU5ZY20zczZOVm1pS0FPTCtlSjd5NWhwMHBUOXdvVHgrU2ZrMWZ0SG9VTWIyZFcKTHNKZWRaVTREbjd5cGsrZk1yNWlyS3F3UzdJQzRYZFlBbEtGTU9UeVVuK1o1YlN0L2xnaHE3VmJnUnZrQ1oveAptL3BBYm1aa3pMdDBZY0hvWmRLNWJWZmFhQ290QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUWWppOTh2MG9kdnpxSk9UN3haaHZaYnhCNTREQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkJVdmllcEZhOAp2YUdIK094bzd4S3NlQTF4U3lVQWdxT2dLaHVDY0hGRVV1NHVWQUR0Mm1ZTlBRSkpnWUhKNDl4WWFiUTFHWVBaCnhCaFU4b2VLVlY0QzdxdHE2aDZUU0hSTmtnNFpWamp5bVJsL0VKai9YZHhmRWZHcXZjZ3hOTFZ5cXRiQjUvT3oKUmpEbkpzM0FqaFVPVkczdUlnK3RwbkpLZzdRakVuTk8vM01qeWdYMENSWXJyTHNMYnE4anJiSTdHcm9qZndGeQpZZlFHZU05cjZtVlUrd1Q1UGtsSTRjajhkenRNNVg4VmdTNVpxMjZWZmxSdUZERU14MnRrb2hnR2xPZm9CbzZaCnlVVDhZenBpdDNiT1p2OW85bEliYlhpVUdLZlh3elRvL2R3YnoyWXM1S1RJRWY1dnZvc0V1a1h0UU02TzVJWFQKL1g3ZkNEK1dTODZhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  KUBERNETES_CLIENT_CERT_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJYUJXUFA3eldRZHN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1qWXhOak0xTkRaYUZ3MHlOREV4TWpVeE5qUXdOVEZhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdSU0J2VTB5QjRQRStrbzYKSVEzRE5RUGJIQ3ZpT3JvaDZScTQ1ZDlDS1BVeWtscmdtdk5aWXZiN3VIRDRvajZsUVJBZmlNdjlGNmZReTdVMwpaWWlrMmlrLzBNVVprY0RzZWhwV0d5RGxYZjU4SnhYZ09VNGEzTkhRemNWZmUyUVhVTzdrV0dWdGlqOHhZenFNCjZtZjRrWWQ2UlBBQ1kyUlh6aWttcHA5SmRQcVdncjBKWExqMTA2ZmlVM0p3VDVBMlRqYkUrN090Nnp4VFpsaEoKaGt1b0NWWDRqS3QzM1pJZVhuNTltLytxV1BZL28wa2JvQjEyZ0FKb29ISm5kUzVCZkpsZ0lJSXJlQkMxVFhabQpOQSt4YjBMVEFnUXBwL1RyUjkxcSt3U2JrQ1l0U2swWkZUNStDbTRGNUlGeEk5Yk5LWC8zOEN6TitONk5KMHlBCnQwK2k3d0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JUWWppOTh2MG9kdnpxSk9UN3haaHZaYnhCNQo0REFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbE53anUybm5FRU82MHdhRm92SUNQdUw0TTg4SUR0VUptTHZWCkJoaldnWnJBMEx5eE5GOUtHMXVqaUh3MW9LaTBEUDhQRitUQnJCL1A3d3pqYXNaOGY4TkZ1c0Z3dmxKRkZGMGEKODRKOWsxVjBha2c3VGdhbVQ4Uml5VkN2elFLTHJ1bTNLRGxVNW0yd0d0cnB3cHJFM01vWWUyZVVQN1JncDk4awpzM1FDTm0xN1lQOU5NKzl4TzVnMnB1MGxKM3lJaDZZdGYxSzVZcGEwaW5rc2FMYXlDd2xqdWdSaUZLRlBIT2FLCitYeExqMTZUaUFYQnBMdjI0bENoUXQzbWw3cEk2RFU1MGtXYXBJRThLSWlIU0Y2OEp2ajVVTm1GZ2hrQ1NNZmEKQ1JGVjFlaGg1blBFR1hTaXRoMHRiVTZHaXRwSmpYUHc1MG9NeW1UcExWK2NMdHcySXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  KUBERNETES_CLIENT_KEY_DATA: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBd3grdytEa2UxWmVqemQrdUQwdXVqdHErYlNOTHEwZm5xZDdjYmEwR0FZcml2WlBDCkZncnRnZ082YVBoQXdNWnVFbWVXbkZISUhPTmtCN1dwOUJaUXg5bW45eHladFJUU1hFTmt6M2E1L3dZalN1NXQKV0Y2eWFwanNXOHZRbVRWUEo0TGVOS2d0c3FyeXpoLzVHUitlQUtZSEU5S1hhK20zNWF6UmtBbXZjZzVhaGQwTApNVU01ayt0ZmxEWW45TVVnc01CRTdIWFcyQUF6ZzZPYWJ5SjNCT1ZLZHZqMEdCYmpQTGRJR0NxanY0VFRvOFBtCkhqMGF0T0NUOWRsYUYyQW5vTnh3SzF3VjE0VVBOeGI1R1lmOGxLTzQ1bWZDUENNZlkzZHgvOFU4SHNpdGpNNkkKTWQ4dzBJck5yazdZbmVWTGNDQWtpSWZEdUZEcGxmVm8zWEZDUHdJREFRQUJBb0lCQVFDM2E0VUo4WGdBeEtrZwprQkdwSXpXVjZCNTFyV1ltUGxPUkpZUUVQVStXQjU2Wkl0cWhxZWdWL2JjdmtaNGRHT3JEdGtpbjdXQzFkelBDCjQ0dzlmUFMyeU8zUnB6citNL0tDOUg5QlhwUDlIU0gwQUNrZGx2Y1VxV2dWNm9QT1lZUmsyZXBUaVh4YnBjTFUKN00xV1JwaGFkN2ZUZEhVTzVnY09pZVA5Q0gyNk1naGcxWU5tYy8rU1E3c280VWR2dEovSXBNOFNqbFlQaURUWApiejJpZkdjUGVwL0JxU24ybjRncnNDWG54eHZZb0dKcU95cmtkL2VxL0ZBRHFudDJKSC96Z0JQYkVDODJ4SUh5CnF0ZGpHY2cwSDZqRGp4OWJsRnhYa2ZFK1lxYmY1bEJhVHFUZmxIcmtNV3hjeVl2WnR0bGRnMXVmNFVWdG9QYi8KQVVjbkNVa1JBb0dCQU1UTE5ZbVFCc2E2eGJXb2wxakxQbkh0OGdUVHhEZXZEOCtUVy9sbGVJcGV4dDR0bW5raQpRMWtXUWNBNkVuMzNiZml1Tm9yQ1JWL3QyWGhqTGo0cTNpZXBSV0ltcTl6NHV1b3Y1dGFLU0RXVCthZ0NjaDltCkdUUXRybGw1eFZlK1pVUjRFUHdKbDRwdjF0Y0R4dnFISEhOV1BBSVppR0U3WGVzTEJ5bUV0cC85QW9HQkFQM1QKM0paRUVMdTVxUHlBeUR6V043VGRPMWNVSkZXUEw4akNaU1VWQmtzY1lDcE1DcFZqeGVYd1ZsdTZrY1ZDbVZjUQpIN0N1SkdBRXlUWmlSOGYwMmlMbjlRbHZMT3o4N1JCaEJGeUM5ZmFJYkUvOWFveTU2bmlERHhRTkFwOEMramY0CkxocnBrWlRmU3dETjlkdi9hM1ZvYnl1NFVoMDBjWVpiOU5oN1JvbnJBb0dBZVVubFRVdC9ZYXhyZm5MU0ZOL3YKTkxpNm1VOExlR1psRUVKNlJWUE0zenRheGtURkdET04zckpoQStERzFPeFMweHBNYzJrWTZPN25RZE9mQktIWApHZ3F4d0xTazZDUkV6MkdHbkdQTjdYZXVQMmFDZitlbFVRdDJrWjhEaWZqRzRWUSs0NWZsMW1UbnZNMlBMWWxvCmQ0MkducVN0OFg5dGV4Zm82aVhwaU9FQ2dZRUFtTng2UDlTRjcwZ0VTT3lWcW0ybjVyaEZBRkFWQWFIVnVTVzUKRy9mcGJscU1YMnlrQXd1dkpxYnlteE5rcmxOSlhYRk1aRzY3WVVnQWxVdml4cnppa1pyM3F0TFZUM09Tb1FhTQpSZHBvbml2U2J1bkN2VFZKeTRIQ0Z1VXU2dXcwSEhqTjYwODJhVjJBSWQvbmJMSUoyUThueEVDZzB3MitRSmdvCmdDYmRlRGtDZ1lFQWdMZkpqRFQ4dTlsUEFmY21GY2ZCclNJUlpMUGdQSHd5dHZ3emhlVGZKWDJUREE4QkFoOFQKOUdmWkNRR2pabnk0Zm5QOWQvczBUalBVUktkanpjOWx5cjRpK29SbUl3WnZ3bmdDckRLR1ExdjlhekttU0NBQQpEKzRCQlFMcjJ4Rk9rNDlzUnh5RUZmRTBobDdMNVBiRHlaRlZMWEhML0xQd3o4eTZmaUlmcjY4PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: kubectl-bash-pod
##  namespace: themis-executor-ppycia
#spec:
#  containers:
#    - name: kubectl-bash-container
#      image: bitnami/kubectl:latest
#      command:
#        - "/bin/bash"
#      stdin: true
#      tty: true
#      env:
#        - name: KUBERNETES_CA_CERT_DATA
#          valueFrom:
#            secretKeyRef:
#              name: themis-secrets-k8s
#              key: KUBERNETES_CA_CERT_DATA
#        - name: KUBERNETES_CLIENT_CERT_DATA
#          valueFrom:
#            secretKeyRef:
#              name: themis-secrets-k8s
#              key: KUBERNETES_CLIENT_CERT_DATA
#        - name: KUBERNETES_CLIENT_KEY_DATA
#          valueFrom:
#            secretKeyRef:
#              name: themis-secrets-k8s
#              key: KUBERNETES_CLIENT_KEY_DATA
#        - name: MAIL_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: themis-secrets
#              key: MAIL_PASSWORD
#        - name: OPENSTACK_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: themis-secrets
#              key: OPENSTACK_PASSWORD